blank_issues_enabled: false
contact_links:
  - name: ðŸ“– Documentation
    url: https://boyer-nicolas.github.io/koritsu/
    about: Check the documentation for usage examples and guides
  - name: ðŸ’¬ Discussions
    url: https://github.com/boyer-nicolas/koritsu/discussions
    about: Ask questions and discuss ideas with the community
